# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "rustjsi-embed"
description = "Standalone create/attach builders for RustJSI."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true
