# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "rustjsi-testkit"
description = "Deterministic backend and conformance harness for RustJSI."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rustjsi-backend = { path = "../backend", version = "=0.0.0" }

[lints]
workspace = true
